### ISSUE TITLE
建议删除这个项目

### ISSUE THREAD

**Issue by mstxq17** [zu1k/xray-crack#1]

**Comment by zu1k** [comment]
有fork的了，删掉也没用了吧

**Comment by xuxiaoyuspallow** [comment]
不如把逆向流程写出来，删掉这个项目，从而筛掉一部分人

**Comment by iiiusky** [comment]
> 不如把逆向流程写出来，删掉这个项目，从而筛掉一部分人

主要是想了解如何从go的二进制中提取出私钥or公钥这些东西

**Comment by chinaykc** [comment]
大佬能看下新版如何破解吗？

**Comment by adkinguzi** [comment]
喜欢这种对抗的感觉

**Comment by zu1k** [comment]
@xuxiaoyuspallow 后面闲下来会写的

@iiiusky pem格式的他没掐头去尾，很容易找的

@chinaykc @adkinguzi 不是要跟官方对抗啊，学习目的，这个也是在官方修改验证算法后才开源出来的，所以说即使有新版的也不会发，再说也真的还没有啊
